<?php
class My_courses {
	function fetch_all_courses(){
		$data_['fhm_courses'] = array (
	        [
	            'ABBREV'                => 'BHMCT',
	            'COURSE'                => 'Bachelor of Hotel Management & Catering Technology',
	            'DURATION'              => '4 Years',
	            'PROGRAMME'             => 'Degree Programme',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => '10+2 with English & 45%',
	            'AFFILIATION_APPROVAL'  => 'Uttarakhand Technical University and approved by AICTE',
	            'FEE_PER_SEMESTER'      => '45,000/-',
	            'syllabus_file'         => 'BHMCT-CBCS18.pdf,BHMCT-II-Year-Syllabus-2019-20.pdf',
	            'path_'                 => '',
	        ],
	        [
	            'ABBREV'                => 'BHM',
	            'COURSE'                => 'Bachelor of Hotel Management',
	            'DURATION'              => '4 Years',
	            'PROGRAMME'             => 'Degree Programme',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => '10+2 with English & 45%',
	            'AFFILIATION_APPROVAL'  => 'Kumaun University',
	            'FEE_PER_SEMESTER'      => '41,000/-',
	            'syllabus_file'         => 'BHM-KU.pdf',
	            'path_'                 => '',
	        ],
	        [
	            'ABBREV'                => 'DHMCT',
	            'COURSE'                =>'Diploma in Hotel Management & Catering Technology',
	            'DURATION'              => '3 Years',
	            'PROGRAMME'             => 'Diploma Programme',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => '10+2 with English',
	            'AFFILIATION_APPROVAL'  => 'Uttarakhand Technical Board and approved by AICTE',
	            'FEE_PER_SEMESTER'      => '27,500/-',
	            'syllabus_file'         => 'dhmct.pdf',
	            'path_'                 => '',
	        ],
	        [
	            'ABBREV'                => 'DHA',
	            'COURSE'                => 'Diploma in Hotel Administration',
	            'DURATION'              => '1 Year',
	            'PROGRAMME'             => 'Diploma Programme',
	            'EXTRA'                 => 'with international certification by <b>AHLEI</b> (American Hotel & Lodging Educational Institute)',
	            'ELIGIBILITY'           => '10+2',
	            'AFFILIATION_APPROVAL'  => 'Uttarakhand Open University',
	            'FEE_PER_SEMESTER'      => 'As per the norms of University',
	            'syllabus_file'         => '',
	            'path_'                 => '',
	        ],
	    );

		$data_['ftca_courses'] = array(
			[
	            'ABBREV'                => 'B. Tech. in [CSE, ECE, EEE, ME]',
	            'COURSE'                => 'Bachelor of Technology in [CSE, ECE, EEE, ME]',
	            'DURATION'              => '4 Years',
	            'PROGRAMME'             => 'Degree',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => '10+2 with 45% (40% reserved category)in Physics and  Mathematics as compulsory subjects along with one of the Chemistry/ Biotechnology/  Biology/ Technical Vocational subject/ Computer Science/ Information Technology/ Informatics Practices/ Agriculture/ Engineering Graphics/ Business Studies',
	            'AFFILIATION_APPROVAL'  => 'Uttarakhand Technical University and approved by AICTE',
	            'FEE_PER_SEMESTER'      => '38,500/-',
	            'syllabus_file'         => 'BTech_1ST_Year 2017-18.pdf,BTech_CSE FIRST YEAR 2018-19.pdf,BTech_CSE SECOND YEAR 2018-19.pdf,BTech_CSE THIRD YEAR & FOURTH YEAR 2018-19.pdf,BTech_CSE FIRST YEAR 2019-20.pdf,BTech_CSE SECOND YEAR 2019-20.pdf,BTech_CSE THIRD YEAR & FOURTH YEAR 2019-20.pdf,BTech_ECE FIRST YEAR 2018-19.pdf,BTech_ECE FIRST YEAR 2018-19.pdf,BTech_ECE THIRD YEAR & FOURTH YEAR 2018-19.pdf,BTech_ECE FIRST YEAR 2019-20.pdf,BTech_ECE SECOND YEAR 2019-20.pdf,BTech_ECE THIRD YEAR & FOURTH YEAR 2019-20.pdf,BTech_EEE FIRST YEAR 2018-19.pdf,BTech_EEE SECOND YEAR 2018-19.pdf,BTech_EEE THIRD YEAR & FOURTH YEAR 2018-19.pdf,BTech_EEE FIRST YEAR 2019-20.pdf,BTech_EEE SECOND YEAR 2019-20.pdf,BTech_EEE THIRD YEAR & FOURTH YEAR 2019-20.pdf,BTech_ME FIRST YEAR 2018-19.pdf,BTech_ME SECOND YEAR 2018-19.pdf,BTech_ME THIRD YEAR & FOURTH YEAR 2018-19.pdf,BTech_ME FIRST YEAR 2019-20.pdf,BTech_ME SECOND YEAR 2019-20.pdf,BTech_ME THIRD YEAR & FOURTH YEAR 2019-20.pdf',
	            'path_'                 => '',
	        ],
	        [
	            'ABBREV'                => 'Diploma in [ME, EE]',
	            'COURSE'                => 'Polytechnic Diploma in [ME, EE]',
	            'DURATION'              => '3 Years',
	            'PROGRAMME'             => 'Diploma',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => 'Passed 10th Std./ SSC examination with 35% marks',
	            'AFFILIATION_APPROVAL'  => 'Uttarakhand Technical Board and approved by AICTE',
	            'FEE_PER_SEMESTER'      => '22,500/-',
	            'syllabus_file'         => 'diploma-ME-sem-1.pdf,diploma-ME-sem-2.pdf,diploma-ME-Sem-3.pdf,diploma-ME-Sem-4.pdf,diploma-ME-Sem-5.pdf,diploma-ME-Sem-6.pdf,diploma-EE-sem-1.pdf,diploma-EE-sem-2.pdf,diploma-EE-Sem-3.pdf,diploma-EE-Sem-4.pdf,diploma-EE-Sem-5.pdf,diploma-EE-Sem-6.pdf',
	            'path_'                 => '',
	        ],
	        [
	            'ABBREV'                => 'MCA',
	            'COURSE'                => 'Master of Computer Applications',
	            'DURATION'              => '2 Years',
	            'PROGRAMME'             => 'Degree',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => 'Graduate with 50% (45% for Reserved Category)<a href="#footnote"><sup>*</sup></a>',
	            'AFFILIATION_APPROVAL'  => 'Uttarakhand Technical University and approved by AICTE',
	            'FEE_PER_SEMESTER'      => '44,000/-',
	            'syllabus_file'         => 'MASTER-OF-COMPUTER-APPLICATION.pdf,MCA-2020-2021UTU-With-Bridge-Course-2.pdf',
	            'path_'                 => '',
	        ],
	        [
	            'ABBREV'                => 'BCA',
	            'COURSE'                => 'Bachelor of Computer Applications ',
	            'DURATION'              => '3 Years',
	            'PROGRAMME'             => 'Degree',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => '10+2 with 40% marks & Mathematics as a subject',
	            'AFFILIATION_APPROVAL'  => 'Kumaun University',
	            'FEE_PER_SEMESTER'      => '32,500/-',
	            'syllabus_file'         => 'Revised BCA Syllabus.pdf,bca_revised_syllabus_2019.pdf',
	            'path_'                 => '',
	        ],
	        [
	            'ABBREV'                => 'B.Sc. (H) (Physics, Chemistry, Maths)',
	            'COURSE'                => 'Bachelor in Science (Honours)',
	            'DURATION'              => '3 Years',
	            'PROGRAMME'             => 'Degree',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => '10+2 with PCM',
	            'AFFILIATION_APPROVAL'  => 'Kumaun University',
	            'FEE_PER_SEMESTER'      => '17,500/-',
	            'syllabus_file'         => '',
	            'path_'                 => '',
	        ],
		);

		$data_['fcbm_courses'] = array(
			[
	            'ABBREV'                => 'MBA',
	            'COURSE'                => 'Master of Business Administration',
	            'DURATION'              => '2 Years',
	            'PROGRAMME'             => 'Degree',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => 'Graduate with 50%',
	            'AFFILIATION_APPROVAL'  => 'Uttarakhand Technical University and approved by AICTE',
	            'FEE_PER_SEMESTER'      => '55,000/-',
	            'syllabus_file'         => 'MBA New syllabus 2018-19.pdf,MBA New syllabus 2020-21.pdf',
	            'path_'                 => '',
	        ],
	        [
	            'ABBREV'                => 'BBA',
	            'COURSE'                => 'Bachelor of Business Administration',
	            'DURATION'              => '3 Years',
	            'PROGRAMME'             => 'Degree',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => '10+2 with 40%',
	            'AFFILIATION_APPROVAL'  => 'Kumaun University',
	            'FEE_PER_SEMESTER'      => '32,500/-',
	            'syllabus_file'         => 'BBA_syllabus_NEW.pdf',
	            'path_'                 => '',
	        ],
	        [
	            'ABBREV'                => 'B.Com. (Hons.)',
	            'COURSE'                => 'Bachelor of Commerce (Honours)',
	            'DURATION'              => '3 Years',
	            'PROGRAMME'             => 'Degree',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => '10+2 with 50%',
	            'AFFILIATION_APPROVAL'  => 'Kumaun University',
	            'FEE_PER_SEMESTER'      => '27,500/-',
	            'syllabus_file'         => 'REVISED BCOM HONOURS SYLLABUS.pdf',
	            'path_'                 => '',
	        ],
	        [
	            'ABBREV'                => 'DRM',
	            'COURSE'                => 'Diploma in Retail Management',
	            'DURATION'              => '1 Year',
	            'PROGRAMME'             => 'Diploma',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => '10+2',
	            'AFFILIATION_APPROVAL'  => 'Retailers Association of India (RAI)',
	            'FEE_PER_SEMESTER'      => '15,000/-',
	            'syllabus_file'         => 'Diploma-in-Retail-Management.pdf',
	            'path_'                 => '',
	        ],
		);

		$data_['fps_courses'] = array(
			[
				'ABBREV'                => 'B. Pharm',
	            'COURSE'                => 'Bachelor in Pharmacy',
	            'DURATION'              => '4 Years',
	            'PROGRAMME'             => 'Degree',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => 'Passed 10+2 exam with PCM/PCB/PCMB',
	            'AFFILIATION_APPROVAL'  => 'Uttarakhand Technical University, AICTE & PCI, New Delhi',
	            'FEE_PER_SEMESTER'      => '37,500/-',
	            'syllabus_file'         => 'bpharm.pdf',
	            'path_'                 => '',
			],
			[
				'ABBREV'                => 'B. Pharm (LE)',
	            'COURSE'                => 'Bachelor in Pharmacy Lateral',
	            'DURATION'              => '3 Years',
	            'PROGRAMME'             => 'Degree',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => 'Passed Diploma in Pharmacy with 60% aggregate marks from PCI Recognized Institution',
	            'AFFILIATION_APPROVAL'  => 'Uttarakhand Technical University, AICTE & PCI, New Delhi',
	            'FEE_PER_SEMESTER'      => '37,500/-',
	            'syllabus_file'         => '',
	            'path_'                 => '',
			],
			[
				'ABBREV'                => 'D. Pharm',
	            'COURSE'                => 'Diploma in Pharmacy',
	            'DURATION'              => '2 Years',
	            'PROGRAMME'             => 'Diploma',
	            'EXTRA'                 => '',
	            'ELIGIBILITY'           => 'Passed 10+2 exam with   PCM/ PCB/PCMB',
	            'AFFILIATION_APPROVAL'  => 'Uttarakhand Technical Board, AICTE & PCI, New Delhi',
	            'FEE_PER_SEMESTER'      => '32,500/-',
	            'syllabus_file'         => 'dpharm.pdf',
	            'path_'                 => '',
			],
		);

		$data_['fe_courses'] = array(
		);

		$data_['hostel_'] = array(
			[
				'HOSTELS'				=>'BHABHA~200, TAOGORE~560',
				'FEE'					=>'60,000/-',
				'UNIT'					=>'YEAR',
			]
		);
		return $data_;
	}
}